# Generated by Django 3.1.6 on 2021-03-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pMentHa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='test',
        ),
        migrations.AddField(
            model_name='question',
            name='resposta',
            field=models.ManyToManyField(blank=True, related_name='respostas', to='pMentHa.Answer'),
        ),
    ]
