# Generated by Django 3.2.3 on 2021-05-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pMentHa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='Option',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='Order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='Question',
            new_name='question',
        ),
    ]
