# Generated by Django 3.1.6 on 2021-03-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pMentHa', '0002_auto_20210331_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='fileNameWithStatement',
            new_name='htmlFileName',
        ),
    ]
