# Generated by Django 3.1.6 on 2021-03-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pMentHa', '0002_auto_20210307_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='result',
            new_name='quotation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='resposta',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='pMentHa.answer'),
        ),
    ]
